# Entries in the config file are used to specify the input files and sheets to be processed.
# They should be specified in the order of processing since transactions from multiple files will be concatenated.
#
# Entry fields:
# path: Path to the input file.
# sheet: Name of the sheet in the input file.
# start_row: Row number in the sheet where the transactions start. Uses `Excell-like` indexing (1-based).

csv_delimiter = ";"

price_file = "Prices.toml"

[[entries]]
file_path = "balances.xlsx"
sheet_name = "2023"
start_row = 1

[[entries]]
file_path = "balances.xlsx"
sheet_name = "2024"
start_row = 15

[[entries]]
file_path = "balances.xlsx"
sheet_name = "2025"
start_row = 16
